include:
  - board: xiao_ble//zmk
    shield: xiaord mona2_dongle
    artifact-name: mona2_dongle

  - board: xiao_ble//zmk
    shield: moNa_L
    artifact-name: mona2_left

  - board: xiao_ble//zmk
    shield: moNa_R
    artifact-name: mona2_right

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
